mm/migrate: Don't expose migrate_misplaced_transhuge_page_put() on !CONFIG_TRANSPARENT_HUGEPAGES
The migrate_misplaced_transhuge_page_put() function does not have to
be exposed on !CONFIG_TRANSPARENT_HUGEPAGES - and it also won't build:

  mm/migrate.c:1549:34: error: call to '__build_bug_failed' declared with attribute error: BUILD_BUG failed
  mm/migrate.c:1564:49: error: call to '__build_bug_failed' declared with attribute error: BUILD_BUG failed
  mm/migrate.c:1566:35: error: call to '__build_bug_failed' declared with attribute error: BUILD_BUG failed
  mm/migrate.c:1573:35: error: call to '__build_bug_failed' declared with attribute error: BUILD_BUG failed
  make[1]: *** [mm/migrate.o] Error 1

Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Andrea Arcangeli <aarcange@redhat.com>
Cc: Rik van Riel <riel@redhat.com>
Cc: Mel Gorman <mgorman@suse.de>
Cc: Hugh Dickins <hughd@google.com>
Cc: Thomas Gleixner <tglx@linutronix.de>
Signed-off-by: Ingo Molnar <mingo@kernel.org>