ARM: omap4: Fix standalone OMAP4 build break for board_onenand_init
Commit 8259573b (ARM: OMAP2+: nand: Make board_onenand_init() visible
to board code) caused the the following error:

CC      arch/arm/mach-omap2/board-flash.o
arch/arm/mach-omap2/board-flash.c:102: error: redefinition of 'board_onenand_init'
arch/arm/mach-omap2/board-flash.h:56: note: previous definition of 'board_onenand_init' was here
make[1]: *** [arch/arm/mach-omap2/board-flash.o] Error 1
make: *** [arch/arm/mach-omap2] Error 2

Signed-off-by: Rajendra Nayak <rnayak@ti.com>
[tony@atomide.com: updated description for the regression commit]
Signed-off-by: Tony Lindgren <tony@atomide.com>