mm/migrate: Fix update_mmu_cache_pmd() use
Stephen Rothwell reported this linux-next build failure:

  mm/migrate.c: In function 'migrate_misplaced_transhuge_page_put':
  mm/migrate.c:1666:2: error: incompatible type for argument 3 of 'update_mmu_cache_pmd'

Caused by commit 7f7f03ce3820 ("mm, numa: Implement
migrate-on-fault lazy NUMA strategy for regular and THP pages")
from the tip tree and exposed by commit "x86: convert
update_mmu_cache() and update_mmu_cache_pmd() to functions" from
the akpm tree.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Andrew Morton <akpm@linux-foundation.org>
Link: http://lkml.kernel.org/r/20121210195402.1042a8ea5bfb57bb758007ac@canb.auug.org.au
Signed-off-by: Ingo Molnar <mingo@kernel.org>